# Generated by Django 4.1.6 on 2023-02-09 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_locations'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='contact_no',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
