# Generated by Django 4.1.6 on 2023-02-09 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_user_contact_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='contact_no',
            field=models.TextField(blank=True, null=True),
        ),
    ]
