# Generated by Django 4.1.6 on 2023-02-09 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0012_alter_location_update_automatically'),
        ('authentication', '0004_alter_user_contact_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='locations',
            field=models.ManyToManyField(related_name='user', to='locations.location'),
        ),
    ]
