# Generated by Django 4.1.6 on 2023-02-07 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_location_latest_information_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='latest_information_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
