# Generated by Django 4.1.6 on 2023-02-07 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_alter_location_latest_information_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='name',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
