# Generated by Django 4.1.6 on 2023-02-08 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0005_remove_location_needs_help_location_needs_donation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='severity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
