# Generated by Django 4.1.6 on 2023-02-08 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0006_location_severity'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='city',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
