# Generated by Django 4.1.6 on 2023-02-09 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0007_location_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='county',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
