# Generated by Django 4.1.6 on 2023-02-09 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0008_location_county'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='activity',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
