# Generated by Django 4.1.6 on 2023-02-09 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0009_location_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='maps_url',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
